tunnel: pratikhomeserver
credentials-file: /home/pratikserver/.cloudflared/Token.json #This is a example. Due to security concerns I have replaced the actual token with placeholder token.

ingress:
  # Portainer Dashboard
  - hostname: portainer.pratik-labs.xyz
    service: http://192.168.1.250:80
    
  # Netdata
  - hostname: netdata.pratik-labs.xyz
    service: http://192.168.1.250:80
  
  # NextCloud
  - hostname: nextcloud.pratik-labs.xyz
    service: http://192.168.1.250.80

  # Catch-all (Security)
  - service: http_status:404

