tunnel: pratikhomeserver
credentials-file: /home/pratikserver/.cloudflared/Token.json #This is a example. Due to security concerns I have replaced the actual token with placeholder token.

ingress:
  # Portainer Dashboard
  - hostname: portainer.pratik-labs.xyz
    service: https://192.168.1.250:9443
    originRequest:
      noTLSVerify: true

  # Catch-all (Security)
  - service: http_status:404
