tunnel: pratikhomeserver
credentials-file: /home/pratikserver/.cloudflared/Token.json #This is a example. Due to security concerns I have replaced the actual token with placeholder token.

ingress:
  # Wildcard Ingress Routing
  - hostname: "*.pratik-labs.xyz"
    service: http://192.168.1.250:80 # Throwing all to the NGINX Proxy Manager

  # Catch-all (Security)
  - service: http_status:404

