services:
  # Like Traffic Manager
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'              # HTTP traffic from Cloudflare Tunnel
      - '81:81'              # Admin UI for Nginx (Internal only)
      - '443:443'            # HTTPS traffic
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

  # Container Management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock # The "Brain" connection
      - portainer_data:/data
 
  # System Monitoring
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: always
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/lib/netdata/cache
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # Nextcloud Database
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=${NC_DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${NC_ROOT_PASSWORD}

  # Nextcloud App
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud-db
    volumes:
      - nextcloud_data:/var/www/html
      - /mnt/storage/Photos:/mnt/photos:ro         # Archive (Read-Only)
      - /mnt/storage/Photos/FamilyUploads:/mnt/uploads:rw # Uploads (Read-Write)
    environment:
      - MYSQL_PASSWORD=${NC_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db

# These named volumes are managed by Docker in /var/lib/docker/volumes
volumes:
  nginx_data:
  nginx_letsencrypt:
  portainer_data:
  netdataconfig:
  netdatalib:
  netdatacache:
  nextcloud_db:
  nextcloud_data:
